<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <DebugType>none</DebugType>
    <AssemblyName>SteamLoginLite.Launcher</AssemblyName>
    <RootNamespace>SteamLoginLite.Launcher</RootNamespace>
    <ApplicationIcon>..\Assets\SteamSwitcher.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
